services:
  postgres:
    image: postgres:16
    container_name: kernreactor_postgres
    restart: always
    environment:
      POSTGRES_USER: nuclear_user
      POSTGRES_PASSWORD: nuclear_password
      POSTGRES_DB: nuclear_source
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../data/raw:/data/raw

volumes:
  postgres_data: